#!/usr/bin/env bash

# pcb-main-nautilus-atmega4809
#
# Copyright 2022, Andrew Countryman <apcountryman@gmail.com> and the
# pcb-main-nautilus-atmega4809 contributors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description: pcb-main-nautilus-atmega4809 repository CI schematic PDF generation script.

function error()
{
    local -r message="$1"

    ( >&2 echo "$mnemonic: $message" )
}

function abort()
{
    if [[ "$#" -gt 0 ]]; then
        local -r message="$1"

        error "$message, aborting"
    fi

    exit 1
}

function display_help_text()
{
    echo "NAME"
    echo "    $mnemonic - Generate a PDF of the project's schematic."
    echo "SYNOPSIS"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic"
    echo "OPTIONS"
    echo "    --help"
    echo "        Display this help text."
    echo "    --version"
    echo "        Display the version of this script."
    echo "EXAMPLES"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic"
}

function display_version()
{
    echo "$mnemonic, version $version"
}

function restore_schematic()
{
    if ! git -C "$repository" restore "$schematic"; then
        abort
    fi
}

function generate_schematic_pdf()
{
    local projects; mapfile -t projects < <( git -C "$repository" ls-files '*.kicad_pro' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly projects

    if [[ "${#projects[@]}" -gt 1 ]]; then
        abort "multiple projects found: ${projects[*]}"
    fi

    if [[ "${#projects[@]}" -eq 1 ]]; then
        local -r project="${projects[0]}"
        local -r project_name=$( basename -s .kicad_pro "$project" )
        local -r schematic="$repository/$project_name.kicad_sch"

        if git -C "$repository" ls-files --error-unmatch "$schematic"; then
            if ! sed -i -e "s/GIT_VERSION/$version/g" "$schematic"; then
                restore_schematic
                abort
            fi

            if ! "$repository/utilities/KiAuto/src/eeschema_do" export -a "$schematic" "$repository/$project_name-schematic-pdf"; then
                restore_schematic
                abort
            fi

            restore_schematic
        fi
    fi
}

function main()
{
    local -r script=$( readlink -f "$0" )
    local -r mnemonic=$( basename "$script" )
    local -r repository=$( readlink -f "$( dirname "$script" )/.." )
    local -r version=$( git -C "$repository" describe --match=none --always --dirty --broken )

    while [[ "$#" -gt 0 ]]; do
        local argument="$1"; shift

        case "$argument" in
            --help)
                display_help_text
                exit
                ;;
            --version)
                display_version
                exit
                ;;
            --*)
                ;&
            -*)
                abort "'$argument' is not a supported option"
                ;;
            *)
                abort "'$argument' is not a valid argument"
                ;;
        esac
    done

    generate_schematic_pdf
}

main "$@"
