# pcb-main-nautilus-atmega4809
#
# Copyright 2022, Andrew Countryman <apcountryman@gmail.com> and the
# pcb-main-nautilus-atmega4809 contributors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description: GitHub Actions CI workflow for the pcb-main-nautilus-atmega4809 repository.

name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    analyze-static-shellcheck:
        name: Analyze (static) - shellcheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Analyze
              shell: bash
              run: ./ci/analyze --analyzer shellcheck

    check-klc-compliance-symbols:
        name: Check KLC compliance - symbols
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Check KLC compliance
              shell: bash
              run: ./ci/check-klc-compliance --library-type symbol

    check-klc-compliance-footprints:
        name: Check KLC compliance - footprints
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Check KLC compliance
              shell: bash
              run: ./ci/check-klc-compliance --library-type footprint

    check-electrical-rules-compliance:
        name: Check electrical rules compliance
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad python3-psutil python3-xvfbwrapper xdotool
            - name: Check electrical rules compliance
              shell: bash
              run: ./ci/check-electrical-rules-compliance

    generate-schematic-pdf:
        name: Generate schematic PDF
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad python3-psutil python3-xvfbwrapper xdotool
            - name: Generate schematic PDF
              shell: bash
              run: ./ci/generate-schematic-pdf
            - name: Archive generated schematic PDF
              uses: actions/upload-artifact@v2
              with:
                  name: pcb-main-nautilus-atmega4809-schematic-pdf
                  path: pcb-main-nautilus-atmega4809-schematic-pdf
                  retention-days: 7

    check-design-rules-compliance:
        name: Check design rules compliance
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad python3-psutil python3-xvfbwrapper xdotool
            - name: Check design rules compliance
              shell: bash
              run: ./ci/check-design-rules-compliance

    generate-bom-interactive:
        name: Generate BOM - interactive
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad python3-wxgtk4.0 python3-xvfbwrapper
            - name: Generate BOM
              shell: bash
              run: xvfb-run --auto-servernum ./ci/generate-bom --bom-type interactive
            - name: Archive generated BOM
              uses: actions/upload-artifact@v2
              with:
                  name: pcb-main-nautilus-atmega4809-bom-interactive
                  path: pcb-main-nautilus-atmega4809-bom-interactive.html
                  retention-days: 7

    generate-bom-traditional:
        name: Generate BOM - traditional
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad python3-psutil python3-xlsxwriter python3-xvfbwrapper xdotool
            - name: Generate BOM
              shell: bash
              run: ./ci/generate-bom --bom-type traditional
            - name: Archive generated BOM
              uses: actions/upload-artifact@v2
              with:
                  name: pcb-main-nautilus-atmega4809-bom-traditional
                  path: pcb-main-nautilus-atmega4809-bom-traditional
                  retention-days: 7

    generate-production-files:
        name: Generate production files
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases && sudo apt update && sudo apt install kicad
            - name: Generate production files
              shell: bash
              run: ./ci/generate-production-files
            - name: Archive generated production files
              uses: actions/upload-artifact@v2
              with:
                  name: pcb-main-nautilus-atmega4809-production-files
                  path: pcb-main-nautilus-atmega4809-production-files
                  retention-days: 7
